name: Historical Data Fetch (5 Years)

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: historical-fetch
  cancel-in-progress: false

jobs:
  historical-fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 420  # 7 hours to allow for long-running historical fetch

    env:
      # Required
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Configuration
      ENVIRONMENT: production

      # Python improves logging flush
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run historical data fetch
        run: |
          set -e
          echo "Starting 5-year historical data fetch..."
          python five_years_fetcher.py

      - name: Archive logs and results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: historical-fetch-logs
          path: |
            artifacts/
          retention-days: 30

      - name: Capture environment info
        if: always()
        run: |
          mkdir -p artifacts
          pip freeze > artifacts/pip-freeze.txt
          echo "Workflow completed at: $(date)" > artifacts/workflow-info.txt
          echo "Total runtime: $SECONDS seconds" >> artifacts/workflow-info.txt